cask_args appdir: '~/Applications'

tap 'homebrew/cask'
tap 'homebrew/bundle'
tap 'homebrew/cask-drivers'
tap 'github/gh'

brew 'imagemagick'
brew 'gh'
brew 'openssl'
brew 'readline'
brew 'rbenv'
brew 'xctool'
brew 'z'
brew 'zsh-syntax-highlighting'

cask 'alfred'
cask 'gpg-suite'
cask 'ksdiff'
cask 'microsoft-teams'
cask 'paw'
cask 'proxyman'
cask 'sf-symbols'
cask 'tower'
