cask_args appdir: '/Applications'

tap 'homebrew/cask'
tap 'homebrew/bundle'
tap 'homebrew/cask-drivers'
tap 'github/gh'
tap 'lautis/refined-github-safari'

brew 'hub'
brew 'imagemagick'
brew 'libgit2'
brew 'gh'
brew 'openssl'
brew 'readline'
brew 'rbenv'
brew 'xctool'
brew 'z'
brew 'zsh-syntax-highlighting'

cask '1password6'
cask 'alfred'
cask 'charles'
cask 'github-desktop'
cask 'gpg-suite'
cask 'ksdiff'
cask 'microsoft-teams'
cask 'opensim'
cask 'paw'
cask 'proxyman'
cask 'refined-github-safari'
cask 'sf-symbols'
cask 'sonos'
cask 'tower'
cask 'visual-studio-code'
