cask_args appdir: '/Applications'

tap 'homebrew/cask'
tap 'homebrew/bundle'
tap 'homebrew/cask-drivers'
tap 'lautis/refined-github-safari'

brew 'gist'
brew 'hub'
brew 'imagemagick'
brew 'libgit2'
brew 'openssl'
brew 'readline'
brew 'rbenv'
brew 'tmux'
brew 'xctool'
brew 'z'
brew 'zsh-syntax-highlighting'

cask 'agenda'
cask 'alfred'
cask 'calibre'
cask 'github'
cask 'gpg-suite'
cask 'iterm2'
cask 'kaleidoscope'
cask 'kindle'
cask 'netnewswire'
cask 'opensim'
cask 'paw'
cask 'proxyman'
cask 'sf-symbols'
cask 'skype-for-business'
cask 'slack'
cask 'sonos'
cask 'textmate'
cask 'tower'

# MAS apps
#cask 'smart-json-editor'
#cask 'things'
